### ISSUE TITLE
No color differentiation between files and folders in Netrw

### ISSUE THREAD

**Issue by alexanderjeurissen** [zefei/cake16#10]
I'm a frequent user of Netrw in combination with tpope's vinegar extension.

Most color schemes differentiate highlighting of folders, files and symlinks in a Netrw buffer but cake16 does not.

example of a colorscheme that includes netrw highlighting ( default theme in Vim with light background):
![screen shot 2017-03-12 at 23 14 18](https://cloud.githubusercontent.com/assets/1220084/23836612/5de15de8-077b-11e7-9eee-2b5e59373981.png)

Cake 16:
![screen shot 2017-03-12 at 23 26 27](https://cloud.githubusercontent.com/assets/1220084/23836613/5df2fde6-077b-11e7-9bac-a2e3a927bc5a.png)

**Comment by zefei** [comment]
Thanks @alexanderjeurissen for the report! I just pushed a patch for this. Let me know if the colors feel strange or inappropriate.

**Comment by alexanderjeurissen** [comment]
@zefei Thanks, I thought I'd look at this tonight however seems you already fixed it 👍
